### PR TITLE
new config 'dbProfiling'

### PR DESCRIPTION
**Pull request by egorrishe**

### CODE REVIEW

**Comment by cr0t** [comment]
Hey there, thanks for the new PR!

Could you, please, squash commits into one or two and update their texts? It's not cool to have a repo history with commit messages like 'refactoring' and 'refactoring 2', etc.

Please, google about commit squashing and rewriting git history. When you finish it on your local side you can make a force-push back again to the Github and this PR will be updated.

**Comment by egorrishe** [comment]
Ok, thats it =)

**Comment by cr0t** [comment]
Not the ideal commit message, but anyway they're squashed! :smile:

**Comment by egorrishe** [comment]
Sorry) I'll try to do it better =)

**Pull request merged**
